### PR TITLE
Fix various warnings

### LINKED ISSUE #1501: Adopt latest FairMQ APIs

### PR DESCRIPTION
**Pull request by dennisklein**
Fix #1501 and #1510

### CODE REVIEW

File: examples/MQ/pixelDetector/src/devices/FairMQPixelFileSinkBin.cxx [hunk 1]
```diff
@@ -100,16 +100,18 @@ void FairMQPixelFileSinkBin::Init()
...
 bool FairMQPixelFileSinkBin::StoreData(fair::mq::Parts& parts, int /*index*/)
 {
-    if (parts.Size() == 0)
+    auto numParts = parts.Size();
+
+    if (numParts == 0)
         return true;   // probably impossible, but still check
 
     // expecting even number of parts in the form: header,data,header,data,header,data and so on...
     int nPPE = 2;   // nof parts per event
```
Comment (ChristianTackeGSI) [inline examples/MQ/pixelDetector/src/devices/FairMQPixelFileSinkBin.cxx:109]: I think, `nPPE` is not modified in this context? Can you add a const or even constexpr to it?

**Review by ChristianTackeGSI — APPROVED** [review]

File: examples/MQ/pixelDetector/src/devices/FairMQPixelFileSinkBin.cxx (hunk 1 above)
Comment (dennisklein) [reply examples/MQ/pixelDetector/src/devices/FairMQPixelFileSinkBin.cxx]: done

**Review by rbx — APPROVED** [review]
I like the idea. Assuming the actual behaviour is not that important for this example. @karabowi do you know?

File: Jenkinsfile [hunk 2]
```diff
@@ -1,34 +1,82 @@
...
-    def arch = spec.arch
-    def check = spec.getOrDefault("check", null)
-    def extra = spec.getOrDefault("extra", null)
-    def image = spec.getOrDefault("image", null)
 
     nodes[label] = {
       node(selector) {
-        githubNotify(context: "${prefix}/${label}", description: 'Building ...', status: 'PENDING')
+        githubNotify(context: "${label}", description: "Building ...", status: "PENDING")
         def logpattern = 'build/Testing/Temporary/*.log'
```
Comment (ChristianTackeGSI) [inline Jenkinsfile:70]: Is the `logpattern` still correct this way?

Comment (dennisklein) [reply Jenkinsfile:70]: good point

**Review by rbx — DISMISSED** [review]

File: fairroot/basemq/devices/FairMQUnpacker.h [hunk 3]
```diff
@@ -88,7 +88,7 @@ class FairMQUnpacker : public fair::mq::Device
         }
 
         // check if given channel exist
```
Comment (ChristianTackeGSI) [inline fairroot/basemq/devices/FairMQUnpacker.h:90]: Please also update the copyright header?

File: examples/MQ/pixelDetector/src/devices/FairMQPixelFileSink.cxx [hunk 4]
```diff
@@ -68,7 +68,7 @@ bool FairMQPixelFileSink::StoreData(fair::mq::Parts& parts, int /*index*/)
 
     cleanup.reserve(numParts);
     objectsForBranches.resize(numParts, nullptr);
-    for (int ipart = 0; ipart < numParts; ipart++) {
+    for (decltype(parts.Size()) ipart = 0; ipart < numParts; ipart++) {
```
Comment (ChristianTackeGSI) [inline examples/MQ/pixelDetector/src/devices/FairMQPixelFileSink.cxx:71]: Wouldn't this better fit in the sign-compare commit?

It's not quite related to fChannels at all?

File: examples/MQ/pixelDetector/src/devices/FairMQPixelFileSinkBin.cxx [hunk 5]
```diff
@@ -100,16 +100,18 @@ void FairMQPixelFileSinkBin::Init()
...
 
     // expecting even number of parts in the form: header,data,header,data,header,data and so on...
-    int nPPE = 2;   // nof parts per event
+    constexpr auto nPPE = 2;   // nof parts per event
 
     if (parts.Size() % nPPE >= 1)
         LOG(info) << "received " << parts.Size() << " parts, will ignore last part!!!";
 
-    for (int ievent = 0; ievent < parts.Size() / nPPE; ievent++) {
+    for (decltype(parts.Size()) ievent = 0; ievent < numParts / nPPE; ievent++) {
```
Comment (ChristianTackeGSI) [inline examples/MQ/pixelDetector/src/devices/FairMQPixelFileSinkBin.cxx]: Same: Move to sign compare commit?

File: fairroot/basemq/devices/FairMQUnpacker.h [hunk 6]
```diff
@@ -105,7 +105,7 @@ class FairMQUnpacker : public fair::mq::Device
 
     void Run()
     {
-        fair::mq::Channel& inputChannel = fChannels.at(fInputChannelName).at(0);
+        fair::mq::Channel& inputChannel = fairroot::GetFairMQDeviceChannels(*this).at(fInputChannelName).at(0);
```
Comment (ChristianTackeGSI) [inline fairroot/basemq/devices/FairMQUnpacker.h:108]: Would a `auto&` work here? Would it be a good idea? Or is it better to keep the type explicit?

File: examples/MQ/pixelDetector/src/devices/FairMQPixelFileSink.cxx [hunk 7]
```diff
@@ -1,5 +1,5 @@
 /********************************************************************************
- * Copyright (C) 2014-2022 GSI Helmholtzzentrum fuer Schwerionenforschung GmbH  *
+ * Copyright (C) 2014-2024 GSI Helmholtzzentrum fuer Schwerionenforschung GmbH  *
```
Comment (ChristianTackeGSI) [inline examples/MQ/pixelDetector/src/devices/FairMQPixelFileSink.cxx:2]: Please move the copyright update to the right commit.

File: examples/advanced/Tutorial3/MQ/fileSink/FileSinkFlatBuffers.h [hunk 8]
```diff
@@ -32,7 +32,7 @@ void FileSink<TestDetectorFlatBuffers>::InitTask()
         for (auto it = hits->begin(); it != hits->end(); ++it) {
             TVector3 pos((*it)->x(), (*it)->y(), (*it)->z());
             TVector3 dpos((*it)->dx(), (*it)->dy(), (*it)->dz());
```
Comment (ChristianTackeGSI) [inline examples/advanced/Tutorial3/MQ/fileSink/FileSinkFlatBuffers.h:34]: Update copyright header?

File: fairroot/base/event/FairTimeStamp.h [hunk 9]
```diff
@@ -75,6 +75,7 @@ class FairTimeStamp : public FairMultiLinkedData_Interface
     }
 
     virtual bool operator<(const FairTimeStamp* rValue) const { return GetTimeStamp() < rValue->GetTimeStamp(); }
+    bool operator<(const FairTimeStamp& rhs) const { return GetTimeStamp() < rhs.GetTimeStamp(); }
```
Comment (ChristianTackeGSI) [inline fairroot/base/event/FairTimeStamp.h:78]: Why those getters and not accessing the member variable directly? It is in this exact same class (so it would even work, if it was private)?

**Review by ChristianTackeGSI — COMMENTED** [review]
Okay, took another deeper look. So a few more comments this time.

Will look at the generated warning analysis next time.

**Review by karabowi — COMMENTED** [review]
I would prefer to leave the `virtual operator<` in `FairTimeStamp`,
as well as the corresponding implementations in `MyDigi` and `FairTestDetectorDigi`.
Would it be possible to add `overload` in the daughter classes?

**Comment by dennisklein** [comment]
> I would prefer to leave the `virtual operator<` in `FairTimeStamp`, as well as the corresponding implementations in `MyDigi` and `FairTestDetectorDigi`. Would it be possible to add `overload` in the daughter classes?

I'll remove my commit regarding this from here and we can move it to a separate PR.

File: fairroot/base/event/FairTimeStamp.h (hunk 9 above)
Comment (dennisklein) [reply fairroot/base/event/FairTimeStamp.h:78]: See my answer to @karabowi comment. I will remove these changes from here.

File: examples/MQ/pixelDetector/src/devices/FairMQPixelFileSink.cxx (hunk 4 above)
Comment (dennisklein) [reply examples/MQ/pixelDetector/src/devices/FairMQPixelFileSink.cxx:71]: Ups, indeed, probably chose the wrong commit in a rebase fixup, thx

File: fairroot/basemq/devices/FairMQUnpacker.h (hunk 3 above)
Comment (dennisklein) [reply fairroot/basemq/devices/FairMQUnpacker.h:90]: done

File: examples/MQ/pixelDetector/src/devices/FairMQPixelFileSink.cxx (hunk 4 above)
Comment (dennisklein) [reply examples/MQ/pixelDetector/src/devices/FairMQPixelFileSink.cxx:71]: done

File: examples/advanced/Tutorial3/MQ/fileSink/FileSinkFlatBuffers.h (hunk 8 above)
Comment (dennisklein) [reply examples/advanced/Tutorial3/MQ/fileSink/FileSinkFlatBuffers.h:34]: done

File: fairroot/base/event/FairTimeStamp.h (hunk 9 above)
Comment (dennisklein) [reply fairroot/base/event/FairTimeStamp.h]: done

File: fairroot/basemq/devices/FairMQUnpacker.h (hunk 6 above)
Comment (dennisklein) [reply fairroot/basemq/devices/FairMQUnpacker.h]: done (and changed it to the `GetChannel` api)

**Review by ChristianTackeGSI — APPROVED** [review]
